// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjX3OkKQ-w9kK4LRT4ORufMpIMp4ANvl4',
    appId: '1:95939959881:web:733a24be343edf8c707398',
    messagingSenderId: '95939959881',
    projectId: 'food-app-32b51',
    authDomain: 'food-app-32b51.firebaseapp.com',
    storageBucket: 'food-app-32b51.appspot.com',
    measurementId: 'G-WWXNH9HQL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9OmgHiYKji6NU0VT-KjMtkPrf-wffPAs',
    appId: '1:95939959881:android:af930b6a3d791fea707398',
    messagingSenderId: '95939959881',
    projectId: 'food-app-32b51',
    storageBucket: 'food-app-32b51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQJdjO3JXZQTzfICcRbwU3HN7b29U2kc',
    appId: '1:95939959881:ios:4b14214160128179707398',
    messagingSenderId: '95939959881',
    projectId: 'food-app-32b51',
    storageBucket: 'food-app-32b51.appspot.com',
    iosBundleId: 'com.example.tamangFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQJdjO3JXZQTzfICcRbwU3HN7b29U2kc',
    appId: '1:95939959881:ios:4b14214160128179707398',
    messagingSenderId: '95939959881',
    projectId: 'food-app-32b51',
    storageBucket: 'food-app-32b51.appspot.com',
    iosBundleId: 'com.example.tamangFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjX3OkKQ-w9kK4LRT4ORufMpIMp4ANvl4',
    appId: '1:95939959881:web:e714d0817d093ab0707398',
    messagingSenderId: '95939959881',
    projectId: 'food-app-32b51',
    authDomain: 'food-app-32b51.firebaseapp.com',
    storageBucket: 'food-app-32b51.appspot.com',
    measurementId: 'G-Y6W9YS21JN',
  );
}
